/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

/**
 *
 * @author marianosierraasensio
 */
public class BotonesPanel extends javax.swing.JPanel {

    /**
     * Creates new form BotonesPanel
     */
    public BotonesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        abrirButton = new javax.swing.JButton();
        nuevoButton = new javax.swing.JButton();
        grabarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        jButton11.setText("jButton11");

        setLayout(new java.awt.GridBagLayout());

        abrirButton.setText("Abrir");
        add(abrirButton, new java.awt.GridBagConstraints());

        nuevoButton.setText("Nuevo");
        add(nuevoButton, new java.awt.GridBagConstraints());

        grabarButton.setText("Grabar");
        add(grabarButton, new java.awt.GridBagConstraints());

        editarButton.setText("Editar");
        add(editarButton, new java.awt.GridBagConstraints());

        borrarButton.setText("Borrar");
        add(borrarButton, new java.awt.GridBagConstraints());

        cancelarButton.setText("Cancelar");
        add(cancelarButton, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirButton;
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton grabarButton;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton nuevoButton;
    // End of variables declaration//GEN-END:variables
}
